name: Build and Push Launcher Images

on:
  push:
    branches: [ main, feat/aas_demo ]
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: identity-hub
            context: launchers/identity-hub
            dockerfile: launchers/identity-hub/src/main/docker/Dockerfile

          - name: issuerservice
            context: launchers/issuerservice
            dockerfile: launchers/issuerservice/src/main/docker/Dockerfile

          - name: controlplane
            context: launchers/controlplane
            dockerfile: launchers/controlplane/src/main/docker/Dockerfile

          - name: dataplane
            context: launchers/dataplane
            dockerfile: launchers/dataplane/src/main/docker/Dockerfile

          - name: catalog-server
            context: launchers/catalog-server
            dockerfile: launchers/catalog-server/src/main/docker/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        id: repo
        run: |
          repo_lowercase=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
          echo "repo_lowercase=${repo_lowercase}" >> "$GITHUB_OUTPUT"

      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Build JAR file
        run: |
          ./gradlew -p ${{ matrix.context }} -Ppersistence=true shadowJar

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          build-args:
            JAR=build/libs/${{ matrix.name }}.jar
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo_lowercase }}/${{ matrix.name }}:latest
            ghcr.io/${{ steps.repo.outputs.repo_lowercase }}/${{ matrix.name }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          platforms: linux/amd64,linux/arm64
